language: php

php:
    - 5.5
    - 5.6
    - 7.0

matrix:
    allow_failures:
        - php: 7.0
    fast_finish: true

install: composer install --no-interaction --prefer-source

script: vendor/bin/phpunit --coverage-text

after_script: vendor/bin/coveralls -v --exclude-no-stmt
